[package]
distribution = "2201.12.2"
name = "Test"
org = "nureka"
repository = "local"
version = "0.1.0"

[[dependency]]
name = "http"
org = "ballerina"
repository = "local"
version = "2.14.2"

[build-options]
observabilityIncluded = true
