name: Code Scanning

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 2 * * 1" # Run weekly on Mondays at 2 AM

jobs:
  ballerina-scan:
    name: Ballerina Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set JAVA_HOME environment variable
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Clone static code analysis tool
        run: |
          git clone https://github.com/nureka-rodrigo/static-code-analysis-tool.git
          cd static-code-analysis-tool

      - name: Checkout to sarif branch and build the tool
        run: |
          cd static-code-analysis-tool
          git checkout sarif
          ./gradlew build -x test -x check
        env:
          packagePAT: ${{ secrets.PACKAGE_PAT }}
          packageUser: ${{ secrets.PACKAGE_USER }}

      - name: Pack and push scan tool to local repository
        run: |
          cd static-code-analysis-tool/scan-command/tool-scan
          bal pack
          bal push --repository=local

      - name: Generate SARIF report
        run: |
          bal scan --sarif

      - name: Verify SARIF file exists
        run: |
          if [ ! -f "target/report/scan_results.sarif" ]; then
            echo "Error: SARIF file not found at target/report/scan_results.sarif"
            echo "SARIF generation may have failed"
            exit 1
          fi
          echo "SARIF file generated successfully"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/report/scan_results.sarif
          category: ballerina-scan
